In [1]:
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [2]:
ds = load_dataset("google/civil_comments")

In [3]:
df = pd.DataFrame(ds['train'])
df

,text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit
0,"This is so cool. It's like, 'would you want yo...",0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1,Thank you!! This would make my life a lot less...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
2,This is such an urgent design problem; kudos t...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
3,Is this something I'll be able to install on m...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
4,haha you guys are a bunch of losers.,0.893617,0.021277,0.000000,0.0,0.872340,0.021277,0.0
...,...,...,...,...,...,...,...,...
1804869,"Maybe the tax on ""things"" would be collected w...",0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1804870,What do you call people who STILL think the di...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1804871,"thank you ,,,right or wrong,,, i am following ...",0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0
1804872,Anyone who is quoted as having the following e...,0.621212,0.030303,0.030303,0.0,0.621212,0.045455,0.0
1804873,Students defined as EBD are legally just as di...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0

In [4]:
df['label'] = (df['toxicity'] > 0.5).astype(int)

In [5]:
toxic_df = df[df['label'] == 1]
clean_df = df[df['label'] == 0]

In [6]:
sample_size_per_class = 10000
toxic_sampled = toxic_df.sample(n=sample_size_per_class, random_state=42)
clean_sampled = clean_df.sample(n=sample_size_per_class, random_state=42)

In [7]:
balanced_df = pd.concat([toxic_sampled,clean_sampled]).sample(frac=1,random_state=42).reset_index(drop=True)

In [8]:
X_train, X_val, y_train, y_val = train_test_split(balanced_df['text'], balanced_df['label'], test_size=0.2, stratify = balanced_df['label'], random_state=42)

In [9]:
print(f"Training shapes: {X_train.shape}, Validation shapes: {X_val.shape}")

Training shapes: (16000,), Validation shapes: (4000,)

In [10]:
vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_val_tfidf = vectorizer.transform(X_val)

In [11]:
baseline_model = LogisticRegression(max_iter=1000)
baseline_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [12]:
preds = baseline_model.predict(X_val_tfidf)
print("\n--- BASELINE PERFORMANCE REPORT ---")
print(classification_report(y_val, preds))

--- BASELINE PERFORMANCE REPORT ---
              precision    recall  f1-score   support

           0       0.79      0.89      0.84      2000
           1       0.87      0.77      0.82      2000

    accuracy                           0.83      4000
   macro avg       0.83      0.83      0.83      4000
weighted avg       0.83      0.83      0.83      4000

In [13]:
from datasets import Dataset
from transformers import AutoTokenizer

In [14]:
train_dataset = Dataset.from_pandas(pd.DataFrame({'text': X_train, 'label': y_train}))
val_dataset = Dataset.from_pandas(pd.DataFrame({'text': X_val, 'label': y_val}))

In [15]:
model_ckpt = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

In [16]:
def tokenize_text(examples):
    return tokenizer(examples['text'], truncation=True, padding="max_length", max_length=128)#TO HAVE MAX VC LEN OF 128 CUZ SHORT COMMENTS HERE

In [17]:
print("Tokenizing training data...")
tokenized_train = train_dataset.map(tokenize_text, batched=True)

print("Tokenizing validation data...")
tokenized_val = val_dataset.map(tokenize_text, batched=True)

print("\nTokenization complete! Check out the new columns added to your data:")
print(tokenized_train.column_names)

Tokenizing training data...

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Tokenizing validation data...

Map:   0%|          | 0/4000 [00:00<?, ? examples/s]

Tokenization complete! Check out the new columns added to your data:
['text', 'label', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask']

In [18]:
import numpy as np
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

In [19]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_ckpt, 
    num_labels=2
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [20]:
#we use logits instead of probabilities for the loss function, so we need to use argmax to get the predicted class
#also logits take less computational resources than probabilities, so we use logits for efficiency
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='macro')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

In [21]:
batch_size = 32

training_args = TrainingArguments(
    output_dir="./distilbert-toxicity-model",
    num_train_epochs=3,              # 3 epochs is usually the sweet spot for fine-tuning
    learning_rate=2e-5,              # Standard fine-tuning LR
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,               # Prevents overfitting
    eval_strategy="epoch",   # Evaluate at the end of every epoch
    save_strategy="epoch",           # Save a checkpoint at the end of every epoch
    load_best_model_at_end=True,     # Keep the best performing model
    fp16=True,                       # CRITICAL: Cuts memory usage in half, speeds up training
    logging_steps=50,                # Print updates frequently
)

In [22]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,   # From your previous tokenization step
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
)

In [23]:
trainer.train()

# 6. Save the final model and tokenizer for Day 4 & Day 5
trainer.save_model("./best_toxicity_model")
tokenizer.save_pretrained("./best_toxicity_model")
print("Training complete and model saved locally!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training complete and model saved locally!

In [24]:
model_path = "./best_toxicity_model"
loaded_model = AutoModelForSequenceClassification.from_pretrained(model_path)
inference_trainer = Trainer(model=loaded_model)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [25]:
print("Running predictions on the validation set")
predictions_output = inference_trainer.predict(tokenized_val)

Running predictions on the validation set

In [26]:
raw_logits = predictions_output.predictions
y_preds = np.argmax(raw_logits, axis=-1)
y_true = predictions_output.label_ids

In [27]:
error_df = pd.DataFrame({
    'text': X_val.values,
    'actual_label': y_true,
    'predicted_label': y_preds
})

In [28]:
false_positives = error_df[(error_df['actual_label'] == 0) & (error_df['predicted_label'] == 1)]
false_negatives = error_df[(error_df['actual_label'] == 1) & (error_df['predicted_label'] == 0)]

In [30]:
print(f"\nTotal False Positives (Unfairly Censored): {len(false_positives)}")
print(f"Total False Negatives (Missed Toxicity): {len(false_negatives)}\n")

print(f"\nTotal False Positives (Unfairly Censored): {len(false_positives)}")
print(f"Total False Negatives (Missed Toxicity): {len(false_negatives)}\n")

print(" TOP FALSE POSITIVES (Model thought these were toxic)")

pd.set_option('display.max_colwidth', None)
print(false_positives['text'].sample(min(5, len(false_positives)), random_state=42).to_string(index=False))

print("\nTOP FALSE NEGATIVES (Model missed this toxicity)")
print(false_negatives['text'].sample(min(5, len(false_negatives)), random_state=42).to_string(index=False))

Total False Positives (Unfairly Censored): 258
Total False Negatives (Missed Toxicity): 175


Total False Positives (Unfairly Censored): 258
Total False Negatives (Missed Toxicity): 175

 TOP FALSE POSITIVES (Model thought these were toxic)
....Except that's not how it works.  This isn't about "how many Americans are killed by terrorists."  it goes deeper than that-- it's a values argument.  Muslims are overwhelmingly un-American and do not share the same notions of liberty, freedom, and democracy as we do.  Look at Pew Research polls of the Muslim world:  The overwhelming majority of them believe Sharia Law is the ONLY law.  The majority believe there is only ONE interpretation of Sharia Law, and that it also supersedes any American government writ or law.  The majority of Muslims directly support, indirectly support, or at the very last sympathize with the following people: Islamists, Jihadists, Islamist extremists, Conservative sects of Islam, or variations therein.\n.\nThe Muslim community owes assimilation into our country, not the other way around.
                                                                                                                                                  We already have the largely uncheck economic and territorial rise of what essentially amounts to a Chinese communist dictatorship expanding with few checks. A system with few human rights, a questionable rule of law, few labor rights and few environmental controls. The Chinese system of government is a growing unchecked menace. It is time to wake up. There are dangers to waking up, but fewer than never realizing you are the frog in a pot getting increasingly hot. They are not content to stay within borders and they have played the West for fools by exploiting the wests foolish greed and crazy belief that capitalism is like glove to hand with democracy and freedom (it ain't).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      So far it is a race between the Liberals and the NDP.  Where is what's his name?  The creepy looking guy who the social Cons like.  Does he have a plan?  I haven't heard of it.  So far, he's irrelevant and clueless.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Hypocrite:\nMassachusetts librarian who compared Dr. Seuss books to 'blackface minstrelsy' once dressed as Cat in the Hat\nhttp://www.masslive.com/news/index.ssf/2017/09/dr-seuss-is-racist_librarian_d.html
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Illegals matty, cmon man  😀

TOP FALSE NEGATIVES (Model missed this toxicity)
Will continue to post:  it matters nothing to this fan base if Your Leafs make the playoffs.  If/When they miss, the assembled hordes of that ridiculously-titled group--though brilliant from a marketing view--Leaf Nation, they will all simply shrug and say, oh well, this was just a re-building year anyway.\n\nThis franchise has been, except for infrequent aberrations, god-awful for 5 decades, and if anything, their fans have become more intense, though some of us would use a different adjective other than intense.\n\nIt's a waste of time to point out deficiencies in ownership, management, coaching or players; this fan base doesn't get it, they never will.\n\nThey play courtiers to their unclothed emperor and enablers, whose hand(s) reach deeper and deeper into their pockets all the time with the active and blind encouragement of those whose pockets are being picked.\n\nThese posters who show up and say they need to play this way or that way, more fools.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Hopefully these two criminals are convicted and a judgment or restitution takes away their assets, PFD, and Imig Audio and Video. Those Imig's are shady to say the least... Man up and show up in court!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           what a bunch of baloney, the right are by far more popular in the polls over all clearly.  i suggest you do your resume cause once merged, the ndp are toast
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  As are you.  The difference is your comments are meaningless, inane and utterly lacking in insight or supporting facts.  Mine aren't.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Yippie yay!  We sure scared Kimmee this time, no?  NO!  All we do is talk big with no action and Kim knows it.  I say we bomb their test facilities the next time he shoots off another missile.  Hopefully with General Kelly guiding, Trump will finally have the balls to take action and call Kim's bluff before it's too late.  If Kim retaliates, wipe Pyongyang off the map. The only thing a bully understands is a stronger foe.   Talking, China, sanctions have bee tried but are not the answer.

In [31]:
import shap
import transformers
import scipy as sp

In [32]:
classifier_pipeline = transformers.pipeline(
    "text-classification", 
    model="./best_toxicity_model", 
    tokenizer="./best_toxicity_model",
    return_all_scores=True # SHAP needs probabilities for all classes
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [33]:
explainer = shap.Explainer(classifier_pipeline)
text_to_explain = [
    "Muslims are overwhelmingly un-American and do not share the same notions of liberty. Look at polls of the Muslim world: The majority believe Sharia Law is the ONLY law."
]
shap_values = explainer(text_to_explain)

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [34]:
shap.plots.text(shap_values)